%% Part B.1
load('Lab4_Data.mat');
% plotting all the values from the data given on a graph for a visual
% repersentation as well as a baseline for the encoder and decoder
figure (1)
plot (xspeech)
title('xspeech');

figure (2)
MagSpect(hChannel)
title('hChannel domain (Frequency)');

figure(3)
MagSpect(hLPF2000)
title('hLPF2000 domain (Frequency)');

figure(4)
MagSpect(hLPF2500)
title('hLPF2500 domain (Frequency)');

%%
MagSpect(xspeech)
title('xspeech (Frequency)');

%% Encoder:
% The audio file will be encoded with the following sets of codes below. To
% encode the file, the first step will be to convolute the audio file with
% a low pass filter to ensure the higher frequency are removed. This is
% because it is not needed. Secondly, the convoluted signal are multiplied
% with the Carrier signal function (from osc.m) to ensure efficient
% transmission. At the very end, he product is convoluted with the
% hChannel to get the final encoded signal.

Convolution_1 = conv(xspeech,hLPF2000);
figure(5)
MagSpect(Convolution_1)
title('Convolution of xspeech and hLPF2000');
Carrier = osc(3500,80710,32000);
% fix 6000 
figure(6)
plot(Carrier)
title('Carrier Signal #1');
Mod = Convolution_1.*Carrier;
figure(7)
MagSpect(Mod)
title('Modulated Signal Frequency Domain');
Output = conv(Mod, hChannel);
figure(8)
MagSpect(Output)
title('Encoded Signal Frequency Domain');

%% Decoder:
% To start off, the signal is multiplied with the carrier signal. Secondly,
% the function is convoluted with the second low-pass filter to remove the
% higher frequencies which will return the final signal. 
% %centeral Freq change. 
Carrier_2 = osc(3500,81520,32000);
figure(9)
plot(Carrier_2)
title('Carrier Signal #2');
Demod = Output.*Carrier_2;
figure(10)
MagSpect(Demod)
title('Demodulated Signal Domain (Frequency)');
new_xspeech = conv(Demod, hLPF2500);
figure(11)
plot(new_xspeech)
title('Decoded Signal');
figure(12)
MagSpect(new_xspeech)
sound(new_xspeech,32000)
title('Decoded Signal Domain (Frequency)');

% 1. Encoded the audio file using the hLPF2000 low pass filter
% 2. Carrier signal generated by the osc.m file and the hChannel signal
% 3. Encoded signal is decoded using another carrier signal (from)the osc.m.
% and hLPF25000 low pass filter. 